### ISSUE TITLE
Must using `URLSearchParams` to POST json body

### ISSUE THREAD

**Issue by kerocate** [48Club/bnb-48-ins-indexer#39]
![image](https://github.com/48Club/bnb-48-ins-indexer/assets/11002280/5141ff23-07d7-4fb2-a64b-2f127da1dbf2)

That isn't mentioned in the api doc

**Comment by jwrookie** [comment]
LGTM.
We will optimize it later. Of course, adding what you said now is very good. PR is welcome.

**Comment by du5** [comment]
You need to setup your request.body format,

**Comment by du5** [comment]
and page_size & page is int, not string value
